name: Build_and_Test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Build
      run: mvn clean install --file pom.xml
    - name: Run Tests
      run: mvn test
